### ISSUE TITLE
4.19-4.20 MVP Stage Assignments

### ISSUE THREAD

**Issue by Luodian** [Luodian/Otter#11]
# Liangyu's work
- [ ] add support for Vicuna pretrained LLM, https://github.com/lm-sys/FastChat#vicuna-weights. @liangyuch  
- [ ] support interactive chat (may init from alpaca or vicuna to better support for chat demo) @liangyuch 
- [ ] support language only chat @liangyuch 
- [ ] !!!!support in-context learning example @liangyuch 
- [ ] host collie demo on one or multiple  3090 GPU
  - run `python collie_chat.py --checkpoint_path xxx`

# Bo's work
- [x] check image preprocess (image mean/variance) in (1) finetuning stage on multi-instruct (2) pretraining stage on mmc4. they need to be aligned. @Luodian 
- [ ] check trained model's ability to support (1) interactive chat (2) different instructions. 
- [x] check special tokens are correctly aligned during training and demo evaluation.

# Yuanhan's work
- [x] test accelerator training, or give Bo's access to a prepared environment to test accelerator on 8x32G V100.
- [ ] prepare datasets card, introduce our multi-instruct in-context learning dataset.
- [x] deepspead config, solve hard-code problem.
- [x] review training code;
- [x] Add LoRA

# Data Paths
> We use {azure_blob} as the mounted blob's start path

# Trained Model Paths
1. Train on GQA: {azure_blob}/models/collie9B_gqa

# Helpful Discussion
1. confirm training data for current stage
2. setup demo and support interactive chat.
3. fsdp, 8bit Adam, LoRA for efficient and distributed tuning.
4. support Collie9B inference on consumer GPU
5. enrich instructions from ChatGPT.

**Comment by 5RJ** [comment]
Hello, it seems you have successed in running training on 32G V100 GPUs? If it's true, could you please share the distributed running cmds? I've struggled in it for several days T_T. Looking forward to your early reply.

**Comment by Luodian** [comment]
hi I am contacting people who are still using V100 to run Otter to let some of them to show the commands. What error you have encountered? You can share it with us.

**Comment by Luodian** [comment]
```sh
export PYTHONPATH=.
export CUDA_LAUNCH_BLOCKING=1 
accelerate launch --config_file=./pipeline/accelerate_configs/accelerate_config_fsdp_v100.yaml \
pipeline/train/instruction_following.py \
--pretrained_model_name_or_path=luodian/OTTER-MPT7B-Init  \
--mimicit_path="/mnt/lustre/dwzhou/data/gpt/m3it/vqa/st-vqa/st-vqa_instructions.json" \
--images_path="/mnt/lustre/dwzhou/data/gpt/m3it/vqa/st-vqa/st-vqa_00.json" \
--train_config_ic_path="/mnt/lustre/dwzhou/data/gpt/m3it/vqa/st-vqa/st-vqa_train.json" \
--batch_size=4 \
--num_epochs=1 \
--report_to_wandb \
--wandb_entity=ntu-slab \
--run_name=OTTER-LLaMA7B-densecaption \
--wandb_project=OTTER-LLaMA7B-3mpt  \
--workers=1 \
--lr_scheduler=cosine \
--learning_rate=1e-5 \
--warmup_steps_ratio=0.01 \
```

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: no
downcast_bf16: false
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: false
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 20687
```

**Comment by 5RJ** [comment]
Thanks very much, I want to run it in distribute with deepspeed, but when I change the accelerate config with below( from accelerate_config_zero2_slurm.yaml), I got this error, have you ever met this？
**1.the accelerate config:**
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
use_cpu: false

**2. the submitted cmd**
workspace=$(realpath $(dirname $(dirname $0)))
cd $workspace
export PYTHONPATH=${workspace}:$PYTHONPATH

partition=Model
jobname=$1
LOG_DIR=$workspace/logs/debug
mkdir -p $LOG_DIR
START_TIME=`date +%m%d-%H%M%S`
LOG_FILE=$LOG_DIR/${jobname}_${START_TIME}

GPU_NUM=$2
gpus_per_node=$(($GPU_NUM>8?8:$GPU_NUM))

export MASTER_ADDR=127.0.0.1
MASTER_PORT=6001

export CUDA_LAUNCH_BLOCKING=1 
GLOG_vmodule=MemcachedClient=-1 \
    srun --mpi=pmi2 \
    -p ${partition} -n${GPU_NUM} --gres=gpu:${gpus_per_node} --ntasks-per-node=${gpus_per_node} \
    --cpus-per-task=5 \
    --job-name=$jobname --kill-on-bad-exit=1 \
    --quotatype=auto \
    -x "SH-IDC1-10-198-6-[242,243,110]" \
accelerate launch --config_file=/mnt/lustre/wuruijia/workspace/MLLM/projects/debug/Otter/scripts/zero2.yaml \
pipeline/train/instruction_following.py \
--pretrained_model_name_or_path="/mnt/lustre/share_data/wuruijia/MLLM/models/OTTER-LLaMA7B-INIT"  \
--mimicit_path="/mnt/lustre/share_data/wuruijia/MLLM/data/MIMIC-IT/DC/DC_instructions.json" \
--images_path="/mnt/lustre/share_data/wuruijia/MLLM/data/MIMIC-IT/DC/DC.json" \
--train_config_path="/mnt/lustre/share_data/wuruijia/MLLM/data/MIMIC-IT/DC/DC_train.json" \
--batch_size=4 \
--num_epochs=1 \
--report_to_wandb \
--wandb_entity=ntu-slab \
--run_name=OTTER-LLaMA7B-densecaption \
--wandb_project=OTTER-LLaMA7B-3mpt  \
--workers=1 \
--lr_scheduler=cosine \
--learning_rate=1e-5 \
--warmup_steps_ratio=0.01 \
--model_name="flamingo" \
2>&1 | tee $LOG_FILE > /dev/null &

**3. the error**
![Uploading image.png…]()

**Comment by Luodian** [comment]
`--config_file=/mnt/lustre/wuruijia/workspace/MLLM/projects/debug/Otter/scripts/zero2.yaml`

Basically you can not run the model with zero2 on non A100 GPU. Since it costs around 79G to run it. And if you use fsdp you should set the `num_processes=1` inside the accelerate config and for zero3, it matches with actually used gpu nums (e.g. 8, 16).

**Comment by 5RJ** [comment]
Thanks, I'll try zero3 soon. But the error is as below (the error info img is failed to upload in the last reply), it seems I haven't got a correct setting for the slurm submit cmd, and I wanna ask for the cmd you've successed.
WARNING:torch.distributed.run:                                                                                                                            *****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable
for optimal performance in your application as needed.                                                                                                    *****************************************
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to listen on [::]:29500 (errno: 98 - Address already in use).                                      [W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to listen on [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to listen on [::]:29500 (errno: 98 - Address already in use).                                      [W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
WARNING:torch.distributed.run:
