### ISSUE TITLE
Some questions about dataset construction

### ISSUE THREAD

**Issue by xjtupanda** [Luodian/Otter#119]
Thanks for sharing the inspiring work!  After reading the original paper, I have some questions about the construction of the MIMIC-IT dataset. 

1. Which dataset do the samples in Fig.2(b) come from? Is it PVSG repository?
2. How to get the answers for the sample? Are they manually annotated? I know for the VQA part and the LLaVA part, they are naturally paired with the questions/instructions, how about the PVSG part?
3. How do you get the instructions/queries for the samples? Are they from some specific set of handwritten templates or are they generated by GPT as in LLaVA?

**Comment by Luodian** [comment]
we have release our paper and dataset, please check the new readme!
