### ISSUE TITLE
README examples not visible on 'dark default' background

### ISSUE THREAD

**Issue by maxjeblick** [Luodian/Otter#120]
Thanks a lot for this repo!

On black background, examples are not readable, another font color maybe useful:
![Screenshot 2023-06-05 at 12-45-18 Luodian_Otter 🦦 Otter a multi-modal model based on OpenFlamingo (open-sourced version of DeepMind's Flamingo) trained on MIMIC-IT and showcasing improved instruction-following ability and in-context learning](https://github.com/Luodian/Otter/assets/24281881/06405745-c715-44f9-ade4-94ca35d025bb)

**Comment by king159** [comment]
Thank you for your advice. We will exchange the format of the image to `.jpg` solve this problem.
