### ISSUE TITLE
Is the content of the demo video reproducible?

### ISSUE THREAD

**Issue by luxtiasco** [Luodian/Otter#134]
As far as I know, a lot of work is required besides the joint operation of OpenFlamingo and LLM, such as contextual real-time processing of video streams, as well as low-latency timely responses.

**Comment by Luodian** [comment]
You can try our demo at https://ottervideo.cliangyu.com/. You will notice that it's realtime responded running at a dual-RTX3090. As we say it's a `conceptual video` as we dont really have a Apple Vision Pro to host our Otter on device. 

But who knows, we are also working on quantizations and try to make our model more light and fast. Hope we can make the `conceptual` into an `actual real`.
