### ISSUE TITLE
[evaluation] MMAGIBench can not be accessed

### ISSUE THREAD

**Issue by Maxlinn** [Luodian/Otter#154]
hi to the team, otter seems really interesting!

when i was reading your paper of [MIMIC-IT](https://export.arxiv.org/pdf/2306.05425v1.pdf), i noticed otter model was evaluated on MMAGIBench benchmark, its quotation is 

_[43] MMAGIBench Team. Mmagibench: A universal multi-modal benchmark towards artificial general intelligence. https://github.com/open-mmlab/mmagibench, 2023. 3, 9, 10_

however, the project page of MMAGIBench is not accessible, and i can hardly find more information about this benchmark other than Otter paper, could you please give some hint? thanks in advance!

**Comment by Luodian** [comment]
It's managed by OpenMMLab, they asked us to send our Otter to them for internal benchmarking. Previously they had a plan to release it in early June but delayed for some unknown reasons. According to what I know they are going to release it very soon (probably in this week).

**Comment by Maxlinn** [comment]
thanks for answering!
