### ISSUE TITLE
Configure openai key in Syphus

### ISSUE THREAD

**Issue by SilenceBQ** [Luodian/Otter#183]
I want to use Syphus on your own dataset,but there was an error when requesting the API for openai, and I don't know how to choose **OPENAI_ API_ BASE**, **OPENAI_ API_ VERSION** and **OPENAI_ API_ENGINE**.When I use 'chatgpt0301' or other models as ENGINE, the value of ENGINE cannot be accessed. When I abandon engine and use gpt-3.5-turbo as the model, request failure will still be displayed. 
Can you provide some parameter examples? Thank you!

**Comment by Luodian** [comment]
Actually we use Azure OAI api to query ChatGPT. So the specific names and args may be "little" different. Let me figure out how to set it with OpenAI's official api. 

Thanks for you patience~

**Comment by SilenceBQ** [comment]
I have found a solution. Just delete the ENGINE and VERSION variable and set OPENAI_ API_ BASE="https://api.openai.com/v1/ ",and then modify code in function query_get as shown below.
```
            response = openai.ChatCompletion.create(
                model = "gpt-3.5-turbo",
                messages=messages,
            )
```

**Comment by SilenceBQ** [comment]
Thank you for your letter. I just found out how to use OpenAI to solve this problem. The main problem is that two environment variables need to be deleted, otherwise strange bugs will continue to appear




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Luodian/Otter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Luodian/Otter] Configure openai key in Syphus (Issue #183)





 
Actually we use Azure OAI api to query ChatGPT. So the specific names and args may be "little" different. Let me figure out how to set it with OpenAI's official api.
 
Thanks for you patience~
