### ISSUE TITLE
Could you provide any other links to download MIMIC-IT dataset?

### ISSUE THREAD

**Issue by Hongbin98** [Luodian/Otter#198]
First of all, thanks for your amazing work and your contributions for the community!

However, the download link of the MIMIC-IT dataset (Microsoft 365) does not support continuous download after disconnection, which is difficult for me to download the whole file at a time.

I fail to do this on 4 machines, more than 10 times. So, I wonder if you could provide any other links to download MIMIC-IT dataset?(e.g., google drive)

**Comment by Luodian** [comment]
Since we only have large storage in Onedrive. Let me think if we can use a more convenient source to host our dataset.
