### ISSUE TITLE
ValueError when running otter_image.py

### ISSUE THREAD

**Issue by angelala3252** [Luodian/Otter#215]
Getting this error after running `model.generate` in `otter_image.py`, no matter what my prompts are:
File "/usr/local/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 696, in _prepare_bias_variables
    raise ValueError(
ValueError: Setting a bias on sequences that share a common token termination is not yet supported. Please open an issue if you see this error message (after checking that it doesn't already exist).

**Comment by cliangyu** [comment]
Please specify your transformers version.

**Comment by angelala3252** [comment]
Originally I was using version 4.31.0 but I retried with version 4.29.0 and it works. Thank you!
