### ISSUE TITLE
[dataset] what does CGD mean in MIMIC-IT Eggs

### ISSUE THREAD

**Issue by Maxlinn** [Luodian/Otter#220]
hi to the team, thanks for the effort to release MIMIC-IT, it is really useful!

after i signing off the MIMIC-IT Eggs form and downloading the pre-dumped mmdata(images & video frames) json, i found there is CGD.json and the mmdata for Ego4D dataset is missing, so i'd like to know

1. what CGD.json is
2. is pre-dumped mmdata fro Ego4D not released yet

thanks in advance for your generous help!

**Comment by pufanyi** [comment]
Hello! Thank you for your attention. Regarding `CGD.json`, we have uploaded it to the Hugging Face dataset, and you can download it from [here](https://huggingface.co/datasets/pufanyi/MIMICIT).
