### ISSUE TITLE
Plans to release Flamingov2 model weights

### ISSUE THREAD

**Issue by vishaal27** [Luodian/Otter#223]
Hey, thanks for your great contributions. I saw a comment here (https://twitter.com/BoLi68567011/status/1684028048998559747) that you have trained Flamingo-Llama2-Chat7B and Flamingo-MPT7B models. However, unfortunately I couldn't find the corresponding weights for these models on HF: https://huggingface.co/luodian
Are you planning to release them soon, or if they are already released please let me know where I can access them :)

**Comment by Luodian** [comment]
hi the flamingo one is there~
https://huggingface.co/luodian/Flamingo-Llama2-Chat7B-CC3M/tree/main

**Comment by vishaal27** [comment]
Thanks for the prompt response, can we simply load it like this?

```python
from flamingo.modeling_flamingo import FlamingoForConditionalGeneration
flamingo_model = FlamingoForConditionalGeneration.from_pretrained("luodian/Flamingo-Llama2-Chat7B-CC3M", device_map=auto)
```
Or would the model class still have to be `OtterForConditionalGeneration`?

**Comment by vishaal27** [comment]
Awesome, thanks so much!
