### ISSUE TITLE
Rewrite Open_Flamingo into a 🤗 huggingface model

### ISSUE THREAD

**Issue by king159** [Luodian/Otter#24]
- [x] `configuration_flamingo.py`: write the configuration file of `Flamingo`
- [x] `modeling_flamingo.py`: rewrite the architecture
- [x] load the checkpoint: rename the layers and `.load_state_dict`
- [x] `processing_flamingo.py`: **delay**, as we can use the `transformers.CLIPImageProcessor()` for now
- [x] model special loading: `device_map=auto`
- [x] model special loading: `load_in_8bit=True`
- [x] model forward: give the lost
- [x] model generation: text+image->model->text
- [ ] model card writing: documentation of _Flamingo-9B_

**Comment by Hambaobao** [comment]
How should I use `flamingo_hf` to load open_flamingo? I haven't found the `flamingo_hf` package, and it's not in transformers either.
