### ISSUE TITLE
IdeficsForVisionText2Text does not exist

### ISSUE THREAD

**Issue by zuwenqiang** [Luodian/Otter#247]
Hi to the team! When training with SD_Instruction.json and SD.json, I encountered the following prompt: "IdeficsForVisionText2Text does not exist." I would like to kindly inquire about the potential impact of the absence of IdeficsForVisionText2Text on the training results. Additionally, I am eager to know how I can obtain IdeficsForVisionText2Text. Please note that my current environment aligns with the recommended versions: transformers=4.29.0; torch=2.0.1; accelerate=0.19.0. Your assistance and guidance would be greatly appreciated.

**Comment by Luodian** [comment]
Hi you can just comment out and ignore relevant lines of code about IDefics.

**Comment by zuwenqiang** [comment]
Yes, this solution indeed enables the code to run smoothly. However, I have noticed that IdeficsForVisionText2Text or transformer.model.idefics is required in many places, including other branches. It seems that these packages are essential.

**Comment by Luodian** [comment]
Sorry for make it misleading, it's not essential. It's a internal developed model code and we will remove this dependency in our next PR.

**Comment by zuwenqiang** [comment]
that's ok, thank you kindly for your response.

**Comment by Luodian** [comment]
never mind!
