### ISSUE TITLE
Question about SD format dataset, multi-batch && variable length frame T （train）

### ISSUE THREAD

**Issue by xmc-andy** [Luodian/Otter#255]
Thank you for your great work! I am doing a single prompt-multiple image input task, I have read all the questions and answers, and found similar questions, according to the question instructions, I try to convert the dataset to SD format, and when batchsize=1, the model can Training, but when batchsize is set to >1, the following error occurs: 

batch["net_input"]["patch_images"] = torch.stack([sample["patch_images"] for sample in samples], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [1, 1, 3, 224, 224] at entry 0 and [1, 2, 3, 224, 224] at entry 1

For variable-length image input, is there a way to set the batchsize to be greater than 1?

**Comment by Luodian** [comment]
hi, are you use your own dataset? 

you can only stack two same shape tensor into a batch.

So you want to train them together, you may use different dataloader for variable length frame T. In our SD, the input are all in a two images format.

**Comment by xmc-andy** [comment]
Thanks for your quick reply! Yes, I am using my own dataset, and I am now trying to find a way to do something similar to collate_fn for input images of different lengths.
