### ISSUE TITLE
if there is any data augmentation operation in the code？

### ISSUE THREAD

**Issue by xmc-andy** [Luodian/Otter#294]
Hello authors, please tell me if there is any data augmentation operation in the code. I tried to find it but couldn't find it.

**Comment by Luodian** [comment]
no image augmentation, only resizing.  Since all other operations would affect the content and partially make images not related to QAs.

**Comment by xmc-andy** [comment]
Indeed, image augmentation will affect the content. If "small range rotation", "contrast" and "brightness" are added to Otter, it may be helpful for classification tasks. What do you think?

**Comment by Luodian** [comment]
Yes, I think it would be helpful!
