### ISSUE TITLE
[dataset] How to prepare OtterHD datasets?

### ISSUE THREAD

**Issue by yxchng** [Luodian/Otter#296]

**Comment by yxchng** [comment]
I don't quite understand. I don't see any mention of datasets like M3IT there. Isn't OtterHD using more data than mimicit?

**Comment by peiliu0408** [comment]
mark

**Comment by Luodian** [comment]
> I don't quite understand. I don't see any mention of datasets like M3IT there. Isn't OtterHD using more data than mimicit?

you can check the markdown file which describes the format, basically you can easily convert any dataset into this format. That's what we do on our cluster, basically we have 40+ converted datasets like M3IT, SVIT...

I could gradually updated them to the [folder](https://entuedu-my.sharepoint.com/personal/libo0013_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flibo0013%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2FMIMICIT%5FParquets&ga=1). 

I've already updated some files here.
