### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by hxan** [Luodian/Otter#302]
Hello, authors, among the series of pre-trained weights of huggingface, are the weights of Llama all the same?

**Comment by Luodian** [comment]
Yes it's same. But it may differ from llama weights since openflamingo would add cross gates attention layers into llm decoder layers.

**Comment by hxan** [comment]
Hello, author, would you like to ask, does it mean that I only need to download one of the pre-trained weights of about 30GB, and then change the pre-trained model by downloading different final_weights.pt? If so this will help me save a lot of download time
