### ISSUE TITLE
ETA on OtterHD-8B weights

### ISSUE THREAD

**Issue by somepago** [Luodian/Otter#303]
Hi, any time estimate on when the weights will be available?

Thanks!

**Comment by Luodian** [comment]
I would say will not be very soon, probably after CVPR ddl. We then have time and GPU to do some experiments we think important. We wish to release the model then. I guess it's around late Nov to Dec.

**Comment by somepago** [comment]
Thanks for the info. I'll close the issue.

**Comment by yuvalkirstain** [comment]
Awesome work! Would love to get access to the model's weights + inference/demo script :)
