### ISSUE TITLE
about the specific prompt strategies from llava-1.5 (otter-hd-8b)  

### ISSUE THREAD

**Issue by peiliu0408** [Luodian/Otter#307]
As mentioned in the paper, the specific prompt is inspired by LLaVA-1.5. I wonder if a specific prompt is appended to the end of the question, similar to the one used in the VQA task, such as "Answer the question using a single word or phrase."

**Comment by Luodian** [comment]
Yes it's the same as llava's strategy for academic data.

**Comment by peiliu0408** [comment]
Thanks, but I discovered through the fine-tuning code that the data from the same dataset is not organized in a conversation format. Is there any ablation study on this aspect?
