### ISSUE TITLE
Partial Model Weights Saved During Multi-GPU Training

### ISSUE THREAD

**Issue by superjamessyx** [Luodian/Otter#312]
![image](https://github.com/Luodian/Otter/assets/106878193/1717d089-00a7-4819-9396-f122aa729fab)
Thank you for your nice work! I've encountered an issue where training a model with multiple GPUs results in a saved model that only contains partial weights. In contrast, training with a single GPU saves the complete model weights as expected. Could you help me identify any potential issues with my approach? I followed the provided code without modifications.

`export PYTHONPATH=.
RUN_NAME="Otter_MPT7B"
GPU=8
WORKERS=$((${GPU}*2))

echo "Using ${GPU} GPUs and ${WORKERS} workers"
echo "Running ${RUN_NAME}"

accelerate launch --config_file=./pipeline/accelerate_configs/accelerate_config_zero3.yaml \
    --num_processes=${GPU} \
    pipeline/train/instruction_following.py \
    --pretrained_model_name_or_path=luodian/OTTER-MPT7B-Init \
    --model_name=otter \
    --instruction_format=simple \
    --training_data_yaml=./shared_scripts/Demo_Data.yaml \
    --batch_size=8 \
    --num_epochs=3 \
    --report_to_wandb \
    --wandb_entity=ntu-slab \
    --external_save_dir=./checkpoints \
    --run_name=${RUN_NAME} \
    --wandb_project=Otter_MPTV \
    --workers=${WORKERS} \
    --lr_scheduler=cosine \
    --learning_rate=2e-5 \
    --warmup_steps_ratio=0.01 \
    --save_hf_model \
    --max_seq_len=1024 \`

**Comment by Luodian** [comment]
I have proposed this issue to HF's transformers, you could take a look, adjusting package versions could resolve this isse.

**Comment by superjamessyx** [comment]
> I have proposed this issue to HF's transformers, you could take a look, adjusting package versions could resolve this issue.
> 
> [huggingface/transformers#27293](https://github.com/huggingface/transformers/issues/27293)

Thank you very much!

**Comment by sangnekim** [comment]
Hello. I met same issue.

Although I downgraded transformers version, the issue was not solved. 
Instead of it, I modified the function "save_pretrained"in https://github.com/Luodian/Otter/blob/main/pipeline/train/train_utils.py#L229 like below
```{python}
import deepspeed

def save_pretrained(component, save_path, is_main_process, save_function):
    """Helper function to save pretrained components."""
    params_to_gather = [p for n, p in component.named_parameters()]
    with deepspeed.zero.GatheredParameters(params_to_gather, modifier_rank=0):
       state_dict = {k: v for k, v in component.named_parameters()}
       component.save_pretrained(save_path, state_dict=state_dict)
```
After then, the whole model parameters are saved.

Is it right?
