### ISSUE TITLE
hello，The fine-tuning of the OtterHD-8B model requires at least how much GPU resources?

### ISSUE THREAD

**Issue by dgo2dance** [Luodian/Otter#314]
hello，The fine-tuning of the OtterHD-8B model requires at least how much GPU resources?

**Comment by Luodian** [comment]
At least 4*A100, the GPU memory would be the largest bottleneck, you may use 80G machine to run it. We use 8*A100-80G, and the provided scripts would be easily scaled to larger computes (multiple nodes), as long as you are familiar with slurm.
