### ISSUE TITLE
mismatch the size of datasets

### ISSUE THREAD

**Issue by LinB203** [Luodian/Otter#318]
As the mentioned in paper, the MIMIC-IT dataset has 2.2M instruction qa. But I have downloaded all `x_instruction.json` from Hugging Face. The total number of instruction qa is 1171k. Anything I miss?

VST 32k image-qa
LA 256k image-qa
SN 6k image-qa
SD 16k image-qa
CGD 141k image-qa
E4D 527k video-qa
DC 56k video-qa
TVC 137k video-qa

In a word, 451k image-qa & 720k video-qa, which 1171k qa totally.

**Comment by Luodian** [comment]
The E4D size is incorrect. We have four parts and we may only upload the first part. Let me prepare upload the rest parts accordingly. BUT it may take fews days since they are pretty large.

**Comment by LinB203** [comment]
> The E4D size is incorrect. I think it's because We have four parts and we may only upload the first part. Let me prepare upload the rest parts accordingly. BUT it may take fews days since they are pretty large.

Thanks for your patient reply.

**Comment by LinB203** [comment]
> > That would be much appreciated if it could be uploaded to hugging face. the OneDrive link is too unstable.
> > > The E4D size is incorrect. I think it's because We have four parts and we may only upload the first part. Let me prepare upload the rest parts accordingly. BUT it may take fews days since they are pretty large.
> 
> Sure let me do so. But uploading to HF is also troublesome, sometimes the git process just failed when file exceeds 100G...

I think splitting multiple parts like `DC` does is a good solution! Thanks again for your generous contribution.

**Comment by pufanyi** [comment]
Hello! We are now uploading `DC` and `E4D` to the [huggingface dataset](https://huggingface.co/datasets/pufanyi/MIMICIT). Expected to be completed within 24 hours.
And you can check [this code](https://huggingface.co/datasets/pufanyi/MIMICIT/blob/main/load.py) to learn how to load the dataset (`instruction.json` + `images.parquet`) and check the integrity of the whole dataset.
Thank you!

**Comment by LinB203** [comment]
That's awesome!

**Comment by Luodian** [comment]
E4D is updated here: https://huggingface.co/datasets/pufanyi/MIMICIT/tree/main/data/E4D

**Comment by LinB203** [comment]
Thanks for your great contribution.

**Comment by Li-Qingyun** [comment]
It seems that VST is also mismatched, although VST parquets were updated 7 days ago.

**Comment by Luodian** [comment]
> It seems that VST is also mismatched, although VST parquets were updated 7 days ago.

oh? Doesn't it have 32,893 instruction pairs?

**Comment by Li-Qingyun** [comment]
> > It seems that VST is also mismatched, although VST parquets were updated 7 days ago.
> 
> oh? Doesn't it have 32,893 instruction pairs?

I use [this code](https://huggingface.co/datasets/pufanyi/MIMICIT/blob/main/tools/load.py) to valid.
The parquet in VST is lacked.

**Comment by Li-Qingyun** [comment]
> > It seems that VST is also mismatched, although VST parquets were updated 7 days ago.
> 
> oh? Doesn't it have 32,893 instruction pairs?

indeed 32893 samples, but 9027 missing_image_ids

**Comment by Li-Qingyun** [comment]
By the way, some size seems mismatched with those in the paper, which is inconvenient to check the integrity of the whole dataset.

**Comment by Luodian** [comment]
The size mismatch may come from we iteratively cleaned the dataset after submission. We will update the paper later when numbers are fully confirmed. 

Let me check the VST's missing image_ids then.

**Comment by Li-Qingyun** [comment]
> The size mismatch may come from we iteratively cleaned the dataset after submission. We will update the paper later when numbers are fully confirmed.
> 
> Let me check the VST's missing image_ids then.

okk
thank you very much

I'll also check my downloaded files again!

I've checked E4D CGD SD SN TVC.  And I'm re-downloading VST and LA to check again. LA is failed to load.

**Comment by Li-Qingyun** [comment]
@Luodian Hi, LA loadding meets error.
![image](https://github.com/Luodian/Otter/assets/79644233/0369693b-c939-45ce-b1f1-690c84741723)

**Comment by Luodian** [comment]
> @Luodian Hi, LA parquet loadding meets error. I've downloaded for twice. ![image](https://private-user-images.githubusercontent.com/79644233/291622382-0369693b-c939-45ce-b1f1-690c84741723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTgxODEsIm5iZiI6MTcwMjk5Nzg4MSwicGF0aCI6Ii83OTY0NDIzMy8yOTE2MjIzODItMDM2OTY5M2ItYzkzOS00NWNlLWIxZjEtNjkwYzg0NzQxNzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE0NTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNWEyMjQwMWE3ZDM4ZWYyYjljNGNmN2I5ZWRjODUwMjQ0ZWQ1YjkzYzM1YjRlMmU0MDQ3Mzk3ZDljODcwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4HyG6jlugsIb9eH14M92TOBPZvRaSNXMIAlDxny2y28)

Please take a look at this issue, iteratively loading would address it.

**Comment by Li-Qingyun** [comment]
which issue 555

**Comment by Luodian** [comment]
This: https://github.com/Luodian/Otter/issues/320

**Comment by Li-Qingyun** [comment]
@Luodian Thanks very very very very much, LA is okay.
Now only VST lacks some samples.

Again, thanks for your brilliant work and repo and your help, which teaches me a lot!
