### ISSUE TITLE
otter-9b-hf disappeared, where to get otter support.

### ISSUE THREAD

**Issue by Li-Qingyun** [Luodian/Otter#324]
Hi, thanks for your great work. It seems that luodian/otter-9b-hf disappeared. Otter, not OtterHD

**Comment by Luodian** [comment]
It's renamed and it's here.

https://huggingface.co/luodian/OTTER-LLaMA7B-Init

**Comment by Li-Qingyun** [comment]
> It's renamed and it's here.
> 
> https://huggingface.co/luodian/OTTER-LLaMA7B-Init

But `This weight is for initilizing training for Otter. It's directly converted from Openflamingo.`

Isn't there well-trained weight that can be used to align evaluation?

**Comment by Luodian** [comment]
if you are referring to trained weights, we would like to refer you this link: https://huggingface.co/luodian/OTTER-Image-MPT7B

Thanks!

**Comment by Li-Qingyun** [comment]
[Cry], LLAMA is required, 555
