### ISSUE TITLE
[bug] missing `import pyarrow.parquet as pq` in mimicit_dataset.py

### ISSUE THREAD

**Issue by kxqt** [Luodian/Otter#330]
I find pq.Parquet is used in [https://github.com/Luodian/Otter/blob/main/pipeline/mimicit_utils/mimicit_dataset.py#L222](https://github.com/Luodian/Otter/blob/main/pipeline/mimicit_utils/mimicit_dataset.py#L222) but the package has not been imported.
Maybe we should add `import pyarrow.parquet as pq` in the file.

**Comment by Luodian** [comment]
Thanks! I will fix it.
