### ISSUE TITLE
Where are the data for SD and GSD?

### ISSUE THREAD

**Issue by VictorSanh** [Luodian/Otter#335]
I am confused at where the data live when reading https://github.com/Luodian/Otter/tree/main/mimic-it

In the one drive, I only see a SD folder. is this folder for SD alone? for GSD alone? for both?

Do you have the number of samples?

**Comment by Luodian** [comment]
hi we moved our new files all on huggingface, you can see it here.

https://huggingface.co/datasets/pufanyi/MIMICIT

I think both images and instructions are inside it.

**Comment by VictorSanh** [comment]
thank you! hf datasets makes it so much easier! glad you went this road, it's a huge gain of productivity for the whole community!
