### ISSUE TITLE
Download failure: MIMICIT/CGD/train-00008-of-00053.parquet

### ISSUE THREAD

**Issue by HiHiAllen** [Luodian/Otter#338]
Hello, when I try to download the MIMICIT dataset on Hugging Face, I cannot download this file: 
MIMICIT/CGD/train-00008-of-00053.parquet
The error message is as follows: 
`
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>NWKNFRJ9PMNM79QB</RequestId>
<HostId>fiFTGPxkx0/AprvQPTPamzGyhzcCRosUt0AOuek8oNgb/7eHD6i/5KN/yhSx3RM3bV99/6H20LM=</HostId>
</Error>
`

**Comment by pufanyi** [comment]
Hello! Thank you for pointing out. I'm trying to re-upload the data. Maybe you can use `CGD-Images` and `CGD-Instructions` if urgent.

**Comment by HiHiAllen** [comment]
Thanks for the reply! I will try it tomorrow. I'm currently downloading the rest of the data and have found the same problem with 
 SN/train-00014-of-00016.parquet  and  TVC/train-00052-of-00261.parquet . I'll keep you informed.

**Comment by HiHiAllen** [comment]
Hi, these three files cannot be downloaded： CGD/train-00008-of-00053.parquet   SN/train-00014-of-00016.parquet   TVC/train-00052-of-00261.parquet
Could you please upload it again if you have the time? thx

**Comment by pufanyi** [comment]
OK!

**Comment by pufanyi** [comment]
Hello! I re-uploaded `CGD`, maybe you can check. `SN` and `TVC` are still uploading.

**Comment by HiHiAllen** [comment]
@pufanyi Thx very much.

**Comment by HiHiAllen** [comment]
@pufanyi  Thx a lot

**Comment by pufanyi** [comment]
@HiHiAllen Hello! I have uploaded `SN` and `TVC`, you can check if it is correct.

**Comment by HiHiAllen** [comment]
@pufanyi Download successful! Thank you for your efforts.
