### ISSUE TITLE
Multi-image inference scripts

### ISSUE THREAD

**Issue by vishaal27** [Luodian/Otter#79]
Hello, thanks so much for providing your amazing model. Are there plans to release a colab notebook or example python script for using Otter for in-context learning / multi-image inputs?
Thanks!

**Comment by Luodian** [comment]
Of course, it's easy to extend from the following code to a notebook demo.

```python
from otter import OtterModel
otter_model = OtterModel.from_pretrained("luodian/otter-9b-hf", device_map=auto)
```

let me write a demo tomorrow and include it inside our repo~

**Comment by king159** [comment]
You may refer to the `Mini Demo` section in the [/docs/demo.md](../blob/master/docs/demo.md). A minimal but complete example is provided.

**Comment by Luodian** [comment]
> You may refer to the `Mini Demo` section in the [/docs/demo.md](../blob/master/docs/demo.md). A minimal but complete example is provided.

@vishaal27 Yes, Jinghao has wrote it here. And I uploaded our models to [Huggingface models](https://huggingface.co/luodian/otter-9b-hf/tree/main) today. You are able to download it in a simple way.
