### ISSUE TITLE
Training data examples

### ISSUE THREAD

**Issue by tfka** [Luodian/Otter#90]
Thanks for sharing the amazing project! Can you provide examples of training data to better understand the format of the training data

**Comment by Luodian** [comment]
We are working on releasing our dataset soon! Thanks for your patience, when our dataset is ready, we will also prepare a sample file (including 8 instruction pairs with corresponding in-context samples) to facilitate researchers to quickly prototyping.

**Comment by Luodian** [comment]
> Thanks for sharing the amazing project! Can you provide examples of training data to better understand the format of the training data

we have release our paper and dataset, please check the new readme!
